name: 'Jira Automation Webhook'
description: 'Call a automation webhook if the pull request has a specific status'
branding:
  icon: 'cloud'
  color: 'blue'
inputs:
  GITHUB_TOKEN:
    description: 'Your GitHub token.'
    required: true
  ignore-title:
    description: 'Ignore the pull request title to find issue ids'
    default: 'false'
  ignore-commits:
    description: 'Ignore commit messages to find issue ids'
    default: 'false'
  find-regex-commits:
    description: 'Regex to find issue ids in commit messages'
    default: '/([A-Za-z]{2,4}-\d+)/g'
  find-regex-title:
    description: 'Regex to find issue ids in pull request title'
    default: '/([A-Za-z]{2,4}-\d+)/g'
  approval-threshold:
    description: 'Approvals required (in percent (50%) or as a number (2)) before a pull requests state is "approved"'
    default: '1'
  force-changes-requested:
    description: 'If true, the pull request status is changes_requested regardless of whether the approval_threshold is reached.'
    default: 'true'
  webhook-urls:
    description: 'todo'
    required: true
runs:
  using: 'node20'
  main: 'action/index.js'