name: 'Jira Automation Webhook'
description: 'Call a automation webhook if the pull request has a specific status'
branding:
  icon: 'cloud'
  color: 'blue'
inputs:
  GITHUB_TOKEN:
    description: 'Your GitHub token.'
  urls:
    description: 'todo'
    required: true
runs:
  using: 'node20'
  main: 'action/index.js'